hydra:
  job:
    chdir: False

parameters:
  dataset_name: "cifar10" # huggingface dataset
  batch_size: 128
  num_workers: 8
  device: "cuda"
  overfit_single_batch: True
  log_dir: "logs"
  run_name: mae-uncertainty-${now:%Y-%m-%d-%H-%M}
  log_every_n_steps: 25
  
